server:
  servlet:
    context-path: /payments-service-api
  port: 0
spring:
  application:
    name: payments-service
  data:
    web:
      pageable:
        one-indexed-parameters: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/PAYMENTS_SERVICE
    username: postgres
    password: postgres
  jpa:
    show-sql: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
